// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvPtOwj9xyWk5vE6faqLU2_kkiEY_8dk',
    appId: '1:944716165573:web:4eed6fc5025ca5ae219bac',
    messagingSenderId: '944716165573',
    projectId: 'solution-2024-safety-edu',
    authDomain: 'solution-2024-safety-edu.firebaseapp.com',
    storageBucket: 'solution-2024-safety-edu.appspot.com',
    measurementId: 'G-6T30VZLNW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF7S0EjX66yAtf9qrzekt1N4gVuEfzehM',
    appId: '1:944716165573:android:c0679df4a43f6736219bac',
    messagingSenderId: '944716165573',
    projectId: 'solution-2024-safety-edu',
    storageBucket: 'solution-2024-safety-edu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbY4zsmvvvy1GZ4YpJxws97RUNFuCSmlU',
    appId: '1:944716165573:ios:b85b01a828ca625e219bac',
    messagingSenderId: '944716165573',
    projectId: 'solution-2024-safety-edu',
    storageBucket: 'solution-2024-safety-edu.appspot.com',
    iosBundleId: 'com.example.safetyedu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbY4zsmvvvy1GZ4YpJxws97RUNFuCSmlU',
    appId: '1:944716165573:ios:39bfcf83985cca8a219bac',
    messagingSenderId: '944716165573',
    projectId: 'solution-2024-safety-edu',
    storageBucket: 'solution-2024-safety-edu.appspot.com',
    iosBundleId: 'com.example.safetyedu.RunnerTests',
  );
}
